### ISSUE TITLE
IDEA: Use keyboard to enter pin

### ISSUE THREAD

**Issue by ckcollab** [ckcollab/django-pin-passcode#4]
thanks John

**Comment by Myoldmopar** [comment]
This is done now, right?  Keyboard input seems to be working for me (and it looks like it was added [a while back](https://github.com/ckcollab/django-pin-passcode/commit/f2ed7879d221c1b85408ad21f78211460bbf9f6c).  One nice addition would be to capture the ESC key and have it call the "reset" action.

Great little library, thanks!

**Comment by ckcollab** [comment]
You're correct, and that's not a bad idea... I'll close this one and if you make a new issue I'll be sure to do it!
